index:
  get_started: "Get Started"
  gitee_repo: "Gitee Repo"
  github_repo: "Github Repo"
  features: "Features"
  feature_oop: "OOP design like JDK"
  feature_oop_desc: "We develop libpdk with object oriented programming style, reorganize PHP functions, interface and classes like Java JDK style. To provide developer with a well designed and robust programming interface."
  feature_thread: "Thread safe support"
  feature_thread_desc: "Care about multithread environment, almost all of API are thread safe implementation. You can develop multithread application happily with libpdk, use operation system thread mechanism to improve application performance."
  feature_performance: "High performance"
  feature_performance_desc: "libpdk develop with modern C++ language and deliver to PHP developer as PHP native extension. We borrow many function and class implemention from JDK, C++ standard library and PHP kernel source code. We implment libpdk as fast as we can."
  feature_doc: "Complete documentation"
  feature_doc_desc: "A good opensource project must be well documented, libpdk supply a complete programming manuals and application programming interface documentations online. You can learn libpdk easily by manuals and get API detail usage in API documentations."
  feature_cpp11: "Implement with C++11"
  feature_cpp11_desc: "libpdk itself is big project develop with C++, We use modern C++ standard when coding and very care about the project architecture, code readability and maintainability. Provide application developer with a reliable framework codebase."
  fearure_opensource: "Opensource project"
  feature_opensource_desc: "libpdk is an opensource project adopt the Apache Licence 2.0 licence and code managed with Github platform, You can develope application with libpdk carefree, Just enjoy it!"
  tutorials: "Tutorials"
  latest_posts: "Latest Posts"
  empty_list: "oops, empty"
  sponsor_title: "Sponsor"
  become_sponsor: "How to become sponsor"
  developer_title: "Developer"
  become_developer: "How to become developer"
  partner_title: "Partner"
  become_partner: "How to become partner"
  links_title: "Friend Links"