index:
  get_started: "Get Started"
  gitee_repo: "Gitee Repo"
  github_repo: "Github Repo"
  features: "Features"
  tutorials: "Tutorials"
  latest_posts: "Latest Posts"
  empty_list: "oops, empty"
  sponsor_title: "Sponsor"
  become_sponsor: "How to become sponsor"
  developer_title: "Developer"
  become_developer: "How to become developer"
  partner_title: "Partner"
  become_partner: "How to become partner"
  links_title: "Friend Links"